language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "sudo apt-get update"
  - "sudo apt-get install python-numpy python-scipy"
  # Fetch and install ASE
  #- "curl https://wiki.fysik.dtu.dk/ase-files/python-ase-3.8.1.3440.tar.gz | tar -zvx ; cd python-ase-3.8.1.3440 ; python setup.py install ; cd .."
  - "svn checkout https://svn.fysik.dtu.dk/projects/ase/trunk ase ; cd ase ; python setup.py install ; cd .."
  - "python setup.py install"
script:
  - "cd tests ; python run_tests.py"
notifications:
  email:
    - lars.pastewka@kit.edu
    - j.r.kermode@warwick.ac.uk
