os:
  - linux
  - osx
sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  # Fetch and install ASE
  #- "curl https://wiki.fysik.dtu.dk/ase-files/python-ase-3.9.0.4465.tar.gz | tar -zvx ; cd python-ase-3.9.0.4465 ; python setup.py install ; cd .."
  #- "svn checkout https://svn.fysik.dtu.dk/projects/ase/trunk ase ; cd ase ; python setup.py install ; cd .."
  - "pip install -r requirements.txt"
  - "python setup.py install"
script:
  - "cd tests ; python run_tests.py"
notifications:
  email:
    - lars.pastewka@kit.edu
    - j.r.kermode@warwick.ac.uk
    - adrien.gola@kit.edu
addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
