[build-system]
requires = ["meson>=0.46.0", "meson-python>=0.11.0", "ninja", "numpy"]
build-backend = "mesonpy"

[project]
name = "matscipy"
description = "Generic Python Materials Science tools"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "James Kermode", email = "james.kermode@gmail.com"},
    { name = "Lars Pastewka", email = "lars.pastewka@imtek.uni-freiburg.de" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python"
]
requires-python = ">=3.7.0"
dynamic = [ "version" ]
dependencies = [
    "defusedxml",
    "h5py",
    "igor",
    "matplotlib>=1.0.0",
    "muFFT>=0.24.0",
    "NuMPI>=0.3.1",
    "numpyencoder",
    "openpyxl",
    "Pillow",
    "python-dateutil",
    "pyyaml",
    "requests",
    "scipy",
    "tiffile",
    "numpy"
]

[project.optional-dependencies]
test = []

[project.urls]
documentation = "https://contactengineering.github.io/SurfaceTopography/"
repository = "https://github.com/libAtoms/matscipy"
changelog = "https://github.com/libAtoms/matscipy/blob/master/ChangeLog.md"

[tool.mesonpep517.metadata]
summary = "Read and analyze surface topographies"  # This should actually be deprecated
meson-python-option-name = "python3"
